name: Report Flaky Tests

on:
    workflow_run:
        workflows: ['E2E tests','Playwright Tests']
        types:
            - completed

jobs:
    report-to-issues:
        name: Report to GitHub issues
        runs-on: ubuntu-latest
        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@v3
              with:
                  repository: WordPress/gutenberg
                  ref: trunk
                  path: gutenberg

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - uses: actions/download-artifact@v3
              id: download_artifact
              # Don't fail the job if there isn't any flaky tests report.
              continue-on-error: true
              with:
                  name: flaky-tests-report
                  path: flaky-tests

            - name: Setup Node.js and install dependencies
              if: ${{ steps.download_artifact.outcome == 'success' }}
              uses: gutenberg/.github/setup-node

            - name: Npm build
              if: ${{ steps.download_artifact.outcome == 'success' }}
              # TODO: We don't have to build the entire project, just the action itself.
              run: npm run build:packages

            - name: Report flaky tests
              uses: gutenberg/packages/report-flaky-tests
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  label: 'type: flaky test'
                  artifact-name-prefix: flaky-tests-report
